services:
  - type: web
    name: emotion-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/facerecog.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
